set_property PACKAGE_PIN W14 [get_ports gpio_0_tri_io[0]]
set_property PACKAGE_PIN J20 [get_ports gpio_0_tri_io[1]]    
set_property PACKAGE_PIN P14 [get_ports UART_1_rxd]
set_property PACKAGE_PIN T10 [get_ports UART_1_txd]

set_property IOSTANDARD LVCMOS33 [get_ports {gpio_0_tri_io[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports UART_1_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_1_txd]

set_property PACKAGE_PIN B20 [get_ports Vaux0_v_n]
set_property PACKAGE_PIN C20 [get_ports Vaux0_v_p]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux0_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux0_v_p]
set_property PACKAGE_PIN D18 [get_ports Vaux1_v_n]
set_property PACKAGE_PIN E17 [get_ports Vaux1_v_p]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux1_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux1_v_p]
set_property PACKAGE_PIN M20 [get_ports Vaux2_v_n]
set_property PACKAGE_PIN M19 [get_ports Vaux2_v_p]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux2_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux2_v_p]
set_property PACKAGE_PIN L20 [get_ports Vaux3_v_n]
set_property PACKAGE_PIN L19 [get_ports Vaux3_v_p]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux3_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux3_v_p]
set_property PACKAGE_PIN J14 [get_ports Vaux6_v_n]
set_property PACKAGE_PIN K14 [get_ports Vaux6_v_p]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux6_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux6_v_p]
set_property PACKAGE_PIN L15 [get_ports Vaux7_v_n]
set_property PACKAGE_PIN L14 [get_ports Vaux7_v_p]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux7_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux7_v_p]
set_property PACKAGE_PIN K19 [get_ports iic_1_scl_io]
set_property PACKAGE_PIN J19 [get_ports iic_1_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports iic_1_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports iic_1_sda_io]

